### ISSUE TITLE
Low Level Design Report - 7 Ekim deadline !!

### ISSUE THREAD

**Issue by selimyagci** [selimyagci/Pengo#10]

**Comment by edabicakci** [comment]
1. Introduction
1.1 Object design trade-offs
1.2 Interface documentation guidelines
1.3 Engineering standards (e.g., UML and IEEE)
1.4 Definitions, acronyms, and abbreviations
2. Packages
3. Class Interfaces
4. Glossary
5. References

**Comment by selimyagci** [comment]
Closed.
